### ISSUE TITLE
Warning on clone

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/cookiecutter-pcds-python#16]
I get the following warning which is slightly annoying on a clone of this repository

`}}/_version.py is not a valid attribute name: {{ cookiecutter.folder_name }}/.gitattributes:1`

**Comment by klauer** [comment]
Not sure we can avoid this, unless we can generate `.gitattributes` dynamically somehow and not keep it in the repo?

**Comment by klauer** [comment]
No longer a problem due to our new `.gitattributes` file
