### ISSUE TITLE
Github/landscape integration is untested 

### ISSUE THREAD

**Issue by n-wbrown** [pcdshub/cookiecutter-pcds-python#3]
## Expected Behavior
Landscape's integration is possibly buggy as it was not tested during the work done for pull request #1.

**Comment by klauer** [comment]
The github issue template, PR template both work (see https://github.com/pcdshub/adviewer)

Landscape is on its way out and does not matter. It will be removed in #8.

If we're on the same page, I think this can be closed.

**Comment by n-wbrown** [comment]
Let's get rid of it. Thanks @klauer
